"""phone to users_phone_numbers column name is updated

Revision ID: 8caa4e109b1d
Revises: 1675e6e6d42e
Create Date: 2025-12-19 15:30:08.830995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8caa4e109b1d'
down_revision: Union[str, Sequence[str], None] = '1675e6e6d42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('posts1')
    # op.drop_table('posts')
    # op.drop_table('votes')
    # op.drop_table('users')
    # op.add_column('users_alembic', sa.Column('users_phone_numbers', sa.String(), nullable=True))
    # op.drop_column('users_alembic', 'phone_number')
    op.alter_column('users_alembic', 'phone_number', new_column_name='users_phone_numbers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_alembic', 'users_phone_numbers', new_column_name='phone_number')
    # op.add_column('users_alembic', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    # op.drop_column('users_alembic', 'users_phone_numbers')
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='users_pkey'),
    # sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('votes',
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['post_id'], ['posts1.id'], name=op.f('votes_post_id_fkey'), ondelete='CASCADE'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('votes_user_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('votes_pkey'))
    # )
    # op.create_table('posts',
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    # sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    # )
    # op.create_table('posts1',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('published', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    # sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('posts1_user_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('posts1_pkey'))
    # )
    # ### end Alembic commands ###
